version: 0.2

phases:
  install:
    runtime-versions:
      python: 3.9 # Specify Python version
    commands:
      - pip install --upgrade pip
      - pip install -r requirements.txt pylint  # Install dependencies and pylint

  pre_build:
    commands:
      - python --version  # Confirm Python version
      - pylint $CODEBUILD_SRC_DIR/*.py || true # Static analysis for top-level Python files

  build:
    commands:
      - echo "Building project..."
      - python -m unittest discover  # Run unit tests for the project, if applicable

artifacts:
  files:
    - '*/'  # Include all files in the output artifact
  discard-paths: no  # Keep the directory structure
