version: 0.2

phases:
  install:
    runtime-versions:
      python: 3.9  # Specify Python version
    commands:
      - echo "Installing dependencies..."
      - pip install --upgrade pip
      - pip install -r requirements.txt pylint  flask_sqlalchemy  # Install application dependencies and linting tools

  pre_build:
    commands:
      - echo "Running pre-build checks..."
      - python --version  # Confirm Python version
      - pylint $CODEBUILD_SRC_DIR/*.py  # Static analysis for top-level Python files
      - echo "Pre-build checks completed."

  post_build:
    commands:
      - echo "Post-build phase completed."
      
artifacts:
  files:
    - '**/*'  # Include all files in the output artifact
  discard-paths: no  # Keep the directory structure
  
  
  