version: 0.2

phases:
  install:
    runtime-versions:
      python: 3.9
    commands:
      - echo "Installing dependencies..."
      - pip install --upgrade pip
      - pip install -r requirements.txt pylint boto3 flask_sqlalchemy

  pre_build:
    commands:
      - echo "Running pre-build checks..."
      - python --version
      - pylint $CODEBUILD_SRC_DIR/*.py || echo "Linting completed with warnings/errors."

  build:
    commands:
      - echo "Running application tests..."
      - pytest tests/  # Assuming test cases are in the `tests` directory

  post_build:
    commands:
      - echo "Build and tests completed."

artifacts:
  files:
    - '**/*'  # Include all files
  discard-paths: no
